### ISSUE TITLE
[ci] add codespell

### ISSUE THREAD

**Issue by jameslamb** [rapidsai/deployment#488]
## Description

The `codespell` project can be used to identify common English spelling mistakes in text files. It should be added in CI here.

## Benefits of this work

* fixes and prevents typos, which improves search and removes distractions for readers

## Acceptance Criteria

* every commit merged to `main` passes `codespell` checks

## Approach

Add it to `.pre-commit-config.yaml`, with a block similar to this:

```yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: ["--toml", "pyproject.toml"]
```

Add any relevant configuration in `pyproject.toml`. Example from `rmm`: https://github.com/rapidsai/rmm/blob/b4c43c5fd03cf93fd935343a4e8b2ccfa763afdb/pyproject.toml#L3-L11

And run like this:

```shell
pre-commit run --all-files
```

## Notes

N/A
